### ISSUE TITLE
Wrong url in logfile

### ISSUE THREAD

**Issue by dhover** [Olen/homeassistant-plant#207]
In case of an error the following line is shown in the logfile:
Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue

This url is for core issues.
Please change the url to https://github.com/Olen/homeassistant-plant/issues

**Comment by Olen** [comment]
The correct URL is in the manifest: https://github.com/Olen/homeassistant-plant/blob/master/custom_components/plant/manifest.json

If you look at the integration page, you will see that the Documentation and Known Issues links points to the right URL.

However, since this integration overrides a core integration, my guess is that HA uses the url for the core integration in the logs.
