### ISSUE TITLE
Illuminance multiply

### ISSUE THREAD

**Issue by simon-bd** [Olen/homeassistant-plant#36]
my Mi flora illuminance sensor is below the lip of the pot (measures lower lux than the leaves receive), would it be possible to multiply the sensor value with ex. 3.8 (tested with another sensor (140lux from my flora 540 from mi motion sensor))

Has anyone else found a solution to get better results ?

**Comment by Olen** [comment]
This sounds like a very special use case.
My suggestion would be to create a template sensor that takes the miflora sensor as input and outputs its value * 3.8
Then you use the template sensor as the "remote sensor" for the plant (use "replace sensor" service call to change the illuminance sensor to the template one instead of using the miflora sensor directly)

**Comment by simon-bd** [comment]
Thanks, love the new UI and card!
