### ISSUE TITLE
Image defaults to local .jpg.jpg

### ISSUE THREAD

**Issue by elektrinis** [Olen/homeassistant-plant#4]
Even though image URL is provided by database, the card points to:
`http://server:8123/local/images/plants/acanthus%20ilicifolius.jpg.jpg`
(tested with `acanthus ilicifolius`)

Also it points to a double .jpg extension.

**Comment by Olen** [comment]
The double jpg-extension has been fixed in the flower-card-repo.

In this version of "plant", only the local path is created.  In the branch I made for the core integration, I have some logic, where you can set "image" to "openplantbook" in the config, and it will use the image from openplantbook.
I was a bit hesitant to use a remote image by default, due to privacy and security concerns.

But development of that branch has stalled for a few months because of a discussion about how to handle config parameters as attributes for integrations.

**Comment by elektrinis** [comment]
Maybe the best way would be local caching? Download once and then use local copy?
Some folks would like to upload their own photo, but that needs a nice GUI, which, I'm sure, is a lot of work.

**Comment by slaxor505** [comment]
I'm working on a GUI solution from API end; it's not super complex.
However, we need to have a robust way to display these images from cloud in
HASS.

**Comment by Olen** [comment]
The new version uses images from OpenPlantbook by default.  I'll add a way t use local images shortly.

https://github.com/Olen/homeassistant-plant/tree/new_plant

**Comment by Olen** [comment]
Closing this for now.  It should not be a problem in the new version
