### ISSUE TITLE
Entity is using native unit of measurement 'None' which is not a valid unit for the device class

### ISSUE THREAD

**Issue by WhimsySpoon** [Olen/homeassistant-plant#56]
I have the following errors in Core since upgrading to 2023.1:

```
Entity sensor.plant_14_air_humidity (<class 'custom_components.plant.sensor.PlantCurrentHumidity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.plant_15_illuminance (<class 'custom_components.plant.sensor.PlantCurrentIlluminance'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('illuminance') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.plant_15_soil_moisture (<class 'custom_components.plant.sensor.PlantCurrentMoisture'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('moisture') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.plant_15_temperature (<class 'custom_components.plant.sensor.PlantCurrentTemperature'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.plant_15_air_humidity (<class 'custom_components.plant.sensor.PlantCurrentHumidity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

It appears there were some sensor changes in this release.

**Comment by Olen** [comment]
Thanks, I'll look into it

**Comment by WhimsySpoon** [comment]
Thanks @Olen. Let me know if you need any testing, additional logs etc.

**Comment by julianfj** [comment]
same error here...
Entity sensor.petunias_air_humidity (<class 'custom_components.plant.sensor.PlantCurrentHumidity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.flor_de_pascua_illuminance_2 (<class 'custom_components.plant.sensor.PlantCurrentIlluminance'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('illuminance') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.flor_de_pascua_soil_moisture (<class 'custom_components.plant.sensor.PlantCurrentMoisture'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('moisture') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.flor_de_pascua_temperature_2 (<class 'custom_components.plant.sensor.PlantCurrentTemperature'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.flor_de_pascua_air_humidity (<class 'custom_components.plant.sensor.PlantCurrentHumidity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by posreg** [comment]
exactly the same errors here :

Entity sensor.miflora1_illuminance (<class 'custom_components.plant.sensor.PlantCurrentIlluminance'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('illuminance') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.miflora1_soil_moisture (<class 'custom_components.plant.sensor.PlantCurrentMoisture'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('moisture') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.miflora1_temperature (<class 'custom_components.plant.sensor.PlantCurrentTemperature'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.miflora1_air_humidity (<class 'custom_components.plant.sensor.PlantCurrentHumidity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Do you have any update already ?

Thanks!

**Comment by Olen** [comment]
Added a PR.

https://github.com/Olen/homeassistant-plant/pull/58

Have not tested it extensively yet, but if anyone wants to try, feel free to pull and test.
(Pretty minor changes, so it should not break anything)

**Comment by WhimsySpoon** [comment]
Thanks @Olen. I've just installed the updated files and restarting core. Will keep an eye on it for a couple of hours and report back.

**Comment by WhimsySpoon** [comment]
Hi @Olen. I've been running the fix version for a day without any issues. However, immediately after installing core 2023.2.0 I have the following:

```
Sensor sensor.plant_15_ppfd_mol has device class None, state class measurement and unit mol/s⋅m² thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by Olen** [comment]
I looked into the last log, but I don't really see this as a problem with the integration.
If it has a value, it will be numeric, however if it is unable to calculate the ppf because the illuninace-sensor is unavailable or not configured, this sensor would also be unknown.
In my opinion it would be wrong to report it as e.g. "0" (which would probably remove this log) if it is really unknown...

But there might be other solutions, that I just don't know.

**Comment by WhimsySpoon** [comment]
First of all, apologies for the formatting of the log. I posted my previous message from my phone and hadn't realised it had removed the line breaks until now.

I actually don't think the error is anything to worry about. It was immediately after I had upgraded to Core 2023.2.0 and I have since noticed that the database migration was happening. There was a notification warning that it could impact performance, and it's possible that the value hadn't been populated yet.

I think it's fair to ignore this one, and based on the fact that the original errors have gone with the changes from PR58, I think that can now be merged and this issue closed.

**Comment by Olen** [comment]
Thanks.  

I have already merged, and will push a new release soon.

**Comment by julianfj** [comment]
after update.. same error
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:608
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 13:04:13 (32 occurrences)
Last logged: 18:31:54

Sensor sensor.limonero_conductivity_2 has device class None, state class measurement and unit µS/cm thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.limonero_soil_moisture has device class moisture, state class measurement and unit % thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.limonero_temperature_2 has device class temperature, state class measurement and unit °C thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.limonero_air_humidity has device class humidity, state class measurement and unit % thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.limonero_ppfd_mol has device class None, state class measurement and unit mol/s⋅m² thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by Olen** [comment]
These are different errors than the ones I fixed in the latest PR.

See https://github.com/Olen/homeassistant-plant/issues/56#issuecomment-1413293098 

But I did find some more info about it
https://github.com/home-assistant/core/pull/87004

So I added a simple fix for that as well:

https://github.com/Olen/homeassistant-plant/pull/59

**Comment by ildar170975** [comment]
What about template sensors?
I have plenty of template sensors which may be “None” on HA startup.
As a result my log is flooded by these warnings.
